<?php

declare(strict_types=1);

namespace GiftCards\Service;

use GiftCards\Contract\HasHooks;
use GiftCards\Repository\GiftCardTableRepository;

defined('ABSPATH') || exit;

/**
 * Exposes the gift-card data this plugin keeps through the WordPress Abilities
 * API (WP 6.9+), so the command palette, an MCP server or an AI assistant
 * working inside wp-admin can answer "how much is left on this code?" and
 * "which codes did order 1234 issue?" without anyone opening the database.
 *
 * Every ability is backed by a call that already exists: the
 * {@see GiftCardTableRepository} lookups the storefront uses, and the settings
 * and gift-card flag {@see GiftCardService} resolves for the kit engine.
 * Deliberately absent, because the plugin does not do them:
 *
 *  - issuing a card on demand. Codes are generated by the kit engine when an
 *    order is completed, with a collision-safe loop that is private to it.
 *  - a redemption history. Only the remaining balance is stored, so there is
 *    no per-spend log to report.
 *  - listing every card in the shop. No repository method reads the table
 *    unfiltered, and this is not the place to invent one.
 *
 * On WordPress < 6.9 the Abilities API is absent, the function_exists() guard
 * in registerHooks() makes the whole service a no-op there.
 *
 * Categories:
 *   - giftcards-cards: issued codes and their balances.
 *   - giftcards-setup: how gift cards are configured on this shop.
 */
final class AbilitiesService implements HasHooks
{
    public function __construct(
        private readonly GiftCardTableRepository $repository,
        private readonly GiftCardService $giftCards,
    ) {
    }

    public function registerHooks(): void
    {
        if (! function_exists('wp_register_ability')) {
            // WP < 6.9, or the Abilities API is not loaded. No-op.
            return;
        }

        add_action('wp_abilities_api_categories_init', [$this, 'registerCategories']);
        add_action('wp_abilities_api_init', [$this, 'registerAbilities']);
    }

    public function registerCategories(): void
    {
        if (! function_exists('wp_register_ability_category')) {
            return;
        }

        wp_register_ability_category('giftcards-cards', [
            'label'       => __('Gift cards, issued codes', 'plogins-giftcards'),
            'description' => __('Issued gift card codes, their remaining balance and the order that issued them.', 'plogins-giftcards'),
        ]);

        wp_register_ability_category('giftcards-setup', [
            'label'       => __('Gift cards, setup', 'plogins-giftcards'),
            'description' => __('How gift cards are configured on this shop: the master switch, the code prefix and the checkout label.', 'plogins-giftcards'),
        ]);
    }

    public function registerAbilities(): void
    {
        if (! function_exists('wp_register_ability')) {
            return;
        }

        $this->registerGetCard();
        $this->registerListOrderCards();
        $this->registerGetSettings();
        $this->registerGetProductStatus();
    }

    /**
     * Balance lookup for a single code, the question a merchant is asked on the
     * phone. Backed by {@see GiftCardTableRepository::findByCode()}, the same
     * read the checkout uses when a shopper applies a code.
     */
    private function registerGetCard(): void
    {
        wp_register_ability('giftcards/get-card', [
            'label'        => __('Get a gift card by code', 'plogins-giftcards'),
            'description'  => __('Returns the remaining balance and issuing order for one gift card code, or found = false when the code is unknown. The recipient address is deliberately not returned.', 'plogins-giftcards'),
            'category'     => 'giftcards-cards',
            'input_schema' => [
                'type'       => 'object',
                'required'   => ['code'],
                'properties' => [
                    'code' => ['type' => 'string', 'minLength' => 1, 'maxLength' => 64],
                ],
            ],
            'output_schema' => [
                'type'       => 'object',
                'properties' => [
                    'found'           => ['type' => 'boolean'],
                    'code'            => ['type' => 'string'],
                    'balance'         => ['type' => ['number', 'null']],
                    'order_id'        => ['type' => ['integer', 'null']],
                    'currency'        => ['type' => 'string'],
                ],
            ],
            'execute_callback' => function (array $input): array {
                $code = $this->normalizeCode(isset($input['code']) ? (string) $input['code'] : '');
                $card = $code === '' ? null : $this->repository->findByCode($code);

                if ($card === null) {
                    return [
                        'found'           => false,
                        'code'            => $code,
                        'balance'         => null,
                        'order_id'        => null,
                        'currency'        => get_woocommerce_currency(),
                    ];
                }

                return [
                    'found'           => true,
                    'code'            => $card->code,
                    'balance'         => $card->balance,
                    'order_id'        => $card->order_id,
                    'currency'        => get_woocommerce_currency(),
                ];
            },
            'permission_callback' => [$this, 'canManageShop'],
            'meta'                => ['show_in_rest' => true, 'readonly' => true],
        ]);
    }

    /**
     * The codes one order issued, the same read that prints them on the buyer's
     * order-confirmation page. Bounded by the repository, which caps a single
     * order's cards so the result can never grow without limit.
     */
    private function registerListOrderCards(): void
    {
        wp_register_ability('giftcards/list-order-cards', [
            'label'        => __('List the gift cards an order issued', 'plogins-giftcards'),
            'description'  => __('Lists the gift card codes issued by one order, each with its remaining balance. Returns an empty list when the order issued none.', 'plogins-giftcards'),
            'category'     => 'giftcards-cards',
            'input_schema' => [
                'type'       => 'object',
                'required'   => ['order_id'],
                'properties' => [
                    'order_id' => ['type' => 'integer', 'minimum' => 1],
                ],
            ],
            'output_schema' => [
                'type'       => 'object',
                'properties' => [
                    'order_id' => ['type' => 'integer'],
                    'cards'    => [
                        'type'  => 'array',
                        'items' => [
                            'type'       => 'object',
                            'properties' => [
                                'code'    => ['type' => 'string'],
                                'balance' => ['type' => 'number'],
                            ],
                        ],
                    ],
                    'currency' => ['type' => 'string'],
                ],
            ],
            'execute_callback' => function (array $input): array {
                $orderId = (int) ($input['order_id'] ?? 0);

                return [
                    'order_id' => $orderId,
                    'cards'    => $orderId > 0 ? $this->repository->findByOrderId($orderId) : [],
                    'currency' => get_woocommerce_currency(),
                ];
            },
            'permission_callback' => [$this, 'canManageShop'],
            'meta'                => ['show_in_rest' => true, 'readonly' => true],
        ]);
    }


    /**
     * The configuration actually in force, defaults merged under the stored
     * option, exactly as the engine receives it.
     */
    private function registerGetSettings(): void
    {
        wp_register_ability('giftcards/get-settings', [
            'label'        => __('Get the gift card settings', 'plogins-giftcards'),
            'description'  => __('Returns the gift card configuration in force: whether the feature is on, the code prefix, the checkout discount label, whether codes are shown on the order, and the wording of the email a recipient is sent. This is the shop\'s own configuration, never a recipient address.', 'plogins-giftcards'),
            'category'     => 'giftcards-setup',
            'input_schema' => ['type' => 'object', 'properties' => []],
            'output_schema' => [
                'type'       => 'object',
                'properties' => [
                    'enabled'             => ['type' => 'boolean'],
                    'code_prefix'         => ['type' => 'string'],
                    'fee_label'           => ['type' => 'string'],
                    'show_codes_on_order' => ['type' => 'boolean'],
                    'email_subject'       => ['type' => 'string'],
                    'email_body'          => ['type' => 'string'],
                ],
            ],
            'execute_callback' => function (): array {
                $settings = $this->giftCards->settings();

                return [
                    'enabled'             => (bool) ($settings['enabled'] ?? false),
                    'code_prefix'         => (string) ($settings['code_prefix'] ?? ''),
                    'fee_label'           => (string) ($settings['fee_label'] ?? ''),
                    'show_codes_on_order' => (bool) ($settings['show_codes_on_order'] ?? true),
                    'email_subject'       => (string) ($settings['email_subject'] ?? ''),
                    'email_body'          => (string) ($settings['email_body'] ?? ''),
                ];
            },
            'permission_callback' => [$this, 'canManageShop'],
            'meta'                => ['show_in_rest' => true, 'readonly' => true],
        ]);
    }

    /**
     * Whether a product sells gift cards, read through the same resolver the
     * engine uses, so a variation inherits the parent's flag here too.
     */
    private function registerGetProductStatus(): void
    {
        wp_register_ability('giftcards/get-product-status', [
            'label'        => __('Check whether a product sells gift cards', 'plogins-giftcards'),
            'description'  => __('Returns whether a product is flagged as a gift card, and its current price, which becomes the value of every code that product issues.', 'plogins-giftcards'),
            'category'     => 'giftcards-setup',
            'input_schema' => [
                'type'       => 'object',
                'required'   => ['product_id'],
                'properties' => [
                    'product_id' => ['type' => 'integer', 'minimum' => 1],
                ],
            ],
            'output_schema' => [
                'type'       => 'object',
                'properties' => [
                    'found'        => ['type' => 'boolean'],
                    'product_id'   => ['type' => 'integer'],
                    'is_gift_card' => ['type' => 'boolean'],
                    'price'        => ['type' => ['number', 'null']],
                    'currency'     => ['type' => 'string'],
                ],
            ],
            'execute_callback' => function (array $input): array {
                $productId = (int) ($input['product_id'] ?? 0);
                $product   = $productId > 0 ? wc_get_product($productId) : null;

                if (! $product instanceof \WC_Product) {
                    return [
                        'found'        => false,
                        'product_id'   => $productId,
                        'is_gift_card' => false,
                        'price'        => null,
                        'currency'     => get_woocommerce_currency(),
                    ];
                }

                $price = (string) $product->get_price();

                return [
                    'found'        => true,
                    'product_id'   => $product->get_id(),
                    'is_gift_card' => $this->giftCards->isGiftCardProduct($product),
                    'price'        => $price === '' ? null : (float) $price,
                    'currency'     => get_woocommerce_currency(),
                ];
            },
            'permission_callback' => [$this, 'canEditProducts'],
            'meta'                => ['show_in_rest' => true, 'readonly' => true],
        ]);
    }

    /**
     * Codes and balances are shop data, so the whole card
     * surface sits behind the capability WooCommerce uses for shop management.
     */
    public function canManageShop(): bool
    {
        return current_user_can('manage_woocommerce');
    }

    /**
     * The gift-card flag lives on the product, so anyone who may edit products
     * (and any shop manager) may read it.
     */
    public function canEditProducts(): bool
    {
        return current_user_can('edit_products') || current_user_can('manage_woocommerce');
    }

    /**
     * Codes are stored exactly as they were issued: upper case, letters, digits
     * and dashes only. Normalise an incoming code the same way, so a lower-case
     * or spaced-out code from an agent still finds its row instead of reporting
     * a card as unknown.
     */
    private function normalizeCode(string $code): string
    {
        $code = sanitize_text_field($code);

        return strtoupper((string) preg_replace('/[^A-Za-z0-9\-]/', '', $code));
    }
}
